- name: Python
  logo: python
  url: https://www.python.org/
  color: '#3C78A9'
  projects:
    - url: https://github.com/hackermondev/GitHub-Follower-Bot

- name: JS/TS
  logo: typescript
  url: https://www.typescriptlang.org/
  color: '#3878C6'
  projects:
    - url: https://github.com/is-a-dev/register
    - url: https://github.com/hackermondev/Discord-Level-Helper
